---
language: cpp
compiler:
  - gcc
env:
  matrix:
  - BUILD_TARGET=test
  - BUILD_TARGET=release
install:
  - sudo easy_install cpp-coveralls
before_script:
script:
  - ./scripts/travis_ci_build.sh
after_success:
  - ./scripts/coveralls.sh
