---
language: cpp
compiler:
  - gcc
  - clang
env:
  matrix:
  - BUILD_TARGET=test
  - BUILD_TARGET=release
before_install:
  - ./scripts/travis_ci/setup_compiler.sh
install:
  - sudo easy_install cpp-coveralls
before_script:
script:
  - ./scripts/travis_ci/build.sh
after_success:
  - ./scripts/travis_ci/coveralls.sh
